---
title: "Untitled"
author: "Satoshi"
date: "November 29, 2018"
output: html_document
---

```{r}
library(leaflet)
library(dplyr)
library(geosphere)
library(data.table)
library(ggplot2)
library(lubridate)
```


```{r}
dat_station<- read.csv("Hubway_Stations_as_of_July_2017.csv")
dat_201809<-read.csv("201809-bluebikes-tripdata.csv")

dat_201809_1<- dat_201809%>% mutate(age=2018-birth.year, gender=as.factor(gender))%>% filter(age<115)%>%
  mutate(age_cat=case_when(
    .$age>=10 & .$age<20 ~1,
    .$age>=20 & .$age<30 ~2,
    .$age>=30 & .$age<40 ~3,
    .$age>=40 & .$age<50 ~4,
    .$age>=50 & .$age<60 ~5,
    .$age>=60 & .$age<70 ~6,
    .$age>=70 & .$age<80 ~7,
    .$age>=80 & .$age<90 ~8,
    .$age>=90 ~9), duration_min=tripduration/60,hour=hour(starttime))
```
The oldest alive person is a Japanese aged 115 years. So, all of the people older 115 years old were excluded as measurement error.
[link](https://en.wikipedia.org/wiki/List_of_the_verified_oldest_people)


```{r}
# Distance
setDT(dat_201809_1)[ , dist_km := distGeo(matrix(c(start.station.longitude, start.station.latitude), ncol = 2),matrix(c(end.station.longitude, end.station.latitude), ncol = 2))/1000]
as.data.frame(dat_201809_1)
```
```{r}
dat_201809_1$hour%>% summary
```

```{r}
dat_201809_1%>% lm(dist_km ~ gender+age,data=.)%>% summary
```

```{r}
# Distance
dat_201809_1 %>% group_by(age_cat) %>% summarize(average = mean(dist_km), se=sd(dist_km)/sqrt(n())) %>% 
  ggplot(aes(age_cat, average))+ 
  geom_errorbar(aes(ymin = average - 2*se, ymax = average+2*se), width = 0.25)+
  geom_point()+
  geom_line()+
  scale_x_continuous(breaks=(c(1,2,3,4,5,6,7,8)), labels=c("10-20","20-30","30-40","40-50","50-60","60-70","70-80","80-"))+
  xlab(expression(paste(Age, " (years)")))+
  ylab(expression(paste(Distance," (km)")))
```

```{r}
# Duration
dat_201809_1 %>% group_by(age_cat) %>% summarize(average = mean(duration_min), se=sd(duration_min)/sqrt(n())) %>% 
  ggplot(aes(age_cat, average))+ 
  geom_errorbar(aes(ymin = average - 2*se, ymax = average+2*se), width = 0.25)+
  geom_point()+
  geom_line()+
  scale_x_continuous(breaks=(c(1,2,3,4,5,6,7,8)), labels=c("10-20","20-30","30-40","40-50","50-60","60-70","70-80","80-"))+
  xlab(expression(paste(Age, " (years)")))+
  ylab(expression(paste(Duration," (min)")))
```


# Period of time
```{r}
dat_201809_1%>% ggplot(aes(hour))+
  geom_histogram(binwidth = 0.5)+
  scale_x_continuous(breaks=(c(0,4,8,12,16,20)))+
  xlab("Hour")+
  ylab("Number of users")
```



# Blue bike Stations
# Number of users at each station
```{r}
# Create data frame
dat_201809_station<- dat_201809%>% 
  group_by(start.station.id)%>% summarize(number=n(), start.station.latitude=first(start.station.latitude), start.station.longitude=first(start.station.longitude),start.station.name=first(start.station.name))
```
# Map about number of users at each station 
```{r}
# Distinguish stations by color based on the number of users
getColor <- function(df) {
  sapply(df$number, function(number) {
  if(number %in% 1:500) {
    "green"
  } else if(number %in% 501:2000) {
    "orange"
  } else if(number >2000) {
    "red"
  } else {
    "blue"
  } })
}

icons <- awesomeIcons(
  icon = 'ios-close',
  iconColor = 'black',
  library = 'ion',
  markerColor = getColor(dat_201809_station)
)

leaflet(dat_201809_station) %>% addTiles() %>%
  addAwesomeMarkers(~start.station.longitude
, ~start.station.latitude, icon=icons, label=~as.character(number), popup = ~start.station.name)
```










