---
title: "New Final Satoshi"
author: "Satoshi"
date: "December 6, 2018"
output: html_document
---

```{r}
library(leaflet)
library(dplyr)
library(geosphere)
library(data.table)
library(ggplot2)
library(lubridate)
library(caret)
```

We used all of the data in 2017
# Comparing within 2017
```{r}
# Importing all data in 2017
dat_201701<-read.csv("201701-hubway-tripdata.csv",stringsAsFactors = FALSE)
dat_201702<-read.csv("201702-hubway-tripdata.csv",stringsAsFactors = FALSE)
dat_201703<-read.csv("201703-hubway-tripdata.csv",stringsAsFactors = FALSE)
dat_201704<-read.csv("201704-hubway-tripdata.csv",stringsAsFactors = FALSE)
dat_201705<-read.csv("201705-hubway-tripdata.csv",stringsAsFactors = FALSE)
dat_201706<-read.csv("201706-hubway-tripdata.csv",stringsAsFactors = FALSE)
dat_201707<-read.csv("201707-hubway-tripdata.csv",stringsAsFactors = FALSE)
dat_201708<-read.csv("201708-hubway-tripdata.csv",stringsAsFactors = FALSE)
dat_201709<-read.csv("201709-hubway-tripdata.csv",stringsAsFactors = FALSE)
dat_201710<-read.csv("201710-hubway-tripdata.csv",stringsAsFactors = FALSE)
dat_201711<-read.csv("201711-hubway-tripdata.csv",stringsAsFactors = FALSE)
dat_201712<-read.csv("201712-hubway-tripdata.csv",stringsAsFactors = FALSE)

# Combine them
dat_2017<-rbind(dat_201701, dat_201702,dat_201703,dat_201704,dat_201705,dat_201706,dat_201707,dat_201708,dat_201709,dat_201710,dat_201711,dat_201712)

# Data cleaning
dat_2017_1<- dat_2017%>% filter(!birth.year=="\\N")%>%
  mutate(birth.year=as.numeric(birth.year))%>%
  filter(birth.year>1900 & birth.year<=2017)%>%
  mutate(age=2017-birth.year, gender=as.factor(gender))%>% filter(age<115)%>%
  mutate(age_cat=case_when(
    .$age>=10 & .$age<20 ~1,
    .$age>=20 & .$age<30 ~2,
    .$age>=30 & .$age<40 ~3,
    .$age>=40 & .$age<50 ~4,
    .$age>=50 & .$age<60 ~5,
    .$age>=60 & .$age<70 ~6,
    .$age>=70 & .$age<80 ~7,
    .$age>=80 ~8), duration_min=tripduration/60,hour=hour(starttime))%>%
  mutate(Year=year(starttime), Month=month(starttime))

# Calculation for distance
setDT(dat_2017_1)[ , dist_km := distGeo(matrix(c(start.station.longitude, start.station.latitude), ncol = 2),matrix(c(end.station.longitude, end.station.latitude), ncol = 2))/1000]
dat_2017_1<-as.data.frame(dat_2017_1)
```

```{r}
# Number of users within a day in 2017
dat_2017_1%>% ggplot(aes(hour))+
  geom_histogram(binwidth = 0.5)+
  scale_x_continuous(breaks=(c(0,4,8,12,16,20)))+
  xlab("Hour")+
  ylab("Number of users")
```
Many people uses rush hours (around 8am and 5pm).


```{r}
# Number of users in each month in 2017
dat_2017_1%>% ggplot(aes(Month))+
  geom_bar()+
  scale_x_continuous(breaks=(c(1,2,3,4,5,6,7,8,9,10,11,12)))+
  xlab("Month")+
  ylab("Number of users")
```
They tend to avoid using Bluebike in Winter. 

```{r}
# Distance
dat_2017_1 %>% group_by(age_cat) %>% summarize(average = mean(dist_km), se=sd(dist_km)/sqrt(n())) %>% 
  ggplot(aes(age_cat, average))+ 
  geom_errorbar(aes(ymin = average - 2*se, ymax = average+2*se), width = 0.25)+
  geom_point()+
  geom_line()+
  scale_x_continuous(breaks=(c(1,2,3,4,5,6,7,8)), labels=c("10-20","20-30","30-40","40-50","50-60","60-70","70-80","80-"))+
  xlab(expression(paste(Age, " (years)")))+
  ylab(expression(paste(Distance," (km)")))
```
There is no consistent trend between age and trip distance.


# How much are they making??
```{r}
dat_2017_1%>%group_by(bikeid)%>%summarize(count=n())%>%
  mutate(income=200*count)
```






# Blue bike Stations
```{r}
# Create data frame
dat_station<- read.csv("Hubway_Stations_as_of_July_2017.csv")
dat_2017_station<- dat_2017_1%>% 
  group_by(start.station.id)%>% summarize(number=n(), start.station.latitude=first(start.station.latitude), start.station.longitude=first(start.station.longitude),start.station.name=first(start.station.name))%>% filter(start.station.latitude>0)
summary(dat_2017_station)
```


# Map about number of users at each station 
```{r}
# Distinguish stations by color based on the number of users
getColor <- function(df) {
  sapply(df$number, function(number) {
  if(number %in% 1:4000) {
    "green"
  } else if(number %in% 4001:10000) {
    "orange"
  } else if(number >10000) {
    "red"
  } else {
    "blue"
  } })
}

icons <- awesomeIcons(
  icon = 'ios-close',
  iconColor = 'black',
  library = 'ion',
  markerColor = getColor(dat_2017_station)
)

leaflet(dat_2017_station) %>% addTiles() %>%
  addAwesomeMarkers(~start.station.longitude
, ~start.station.latitude, icon=icons, label=~as.character(number), popup = ~start.station.name)
```